---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crashloop-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - statefulsets/scale
  verbs:
  - get
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crashloop-operator.lauger.de
  resources:
  - crashlooppolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crashloop-operator.lauger.de
  resources:
  - crashlooppolicies/finalizers
  verbs:
  - update
- apiGroups:
  - crashloop-operator.lauger.de
  resources:
  - crashlooppolicies/status
  verbs:
  - get
  - patch
  - update
