apiVersion: crashloop-operator.lauger.de/v1alpha1
kind: CrashLoopPolicy
metadata:
  name: default
  namespace: default
spec:
  watchReasons:
    - CrashLoopBackOff
    - ImagePullBackOff
    - ErrImagePull
    - CreateContainerConfigError
    - InvalidImageName
    - RunContainerError
  restartThreshold: 10
  durationThreshold: "30m"
  allReplicasFailing: true
  targets:
    - Deployment
    - StatefulSet
    - CronJob
  # namespaceSelector:
  #   matchLabels:
  #     env: production
  excludeNamespaces:
    - kube-system
  # excludeWorkloadSelector:
  #   matchLabels:
  #     argocd.argoproj.io/instance: my-app
  dryRun: false
